name: Defacto Engineering
markdown: redcarpet
highlighter: true
authors:
  jurre:
    name: Jurre Stender
    gravatar: 0dff0f9ef3d64ea9bc03a755661886c9
    email: j.stender@defacto.nl
    twitter: jurretweet
    github: jurre
  alexander:
    name: Alexander Jeurissen
    gravatar: c95e2bae7b86397eaae63b1c8488cfb4
    email: a.jeurissen@defacto.nl
    twitter: AlexanderJeuris
    github: alexanderjeurissen
  maarten:
    name: Maarten Jacobs
    gravatar: e2df253ce9ec40bdb620d271e5355a43
    email: m.jacobs@defacto.nl
    twitter:
    github: tarzan
  hugo:
    name: Hugo Veeger
    gravatar: b3164f7cd48eac83bc74ae2dc73f7af6
    email: hugo@defacto.nl
    twitter:
    github: dkhgh
  Marcel:
    name: Marcel Horlings
    gravatar: 4fa144da6e487e02f72bbf23f8c7a3d2
    email: marcel@defacto.nl
    twitter: FatboyPunk
    github: FatboyPunk
